### Accede al sistema como "DESARROLLADOR" y devuelve un token.
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "dev@test.com",
    "password": "dev_password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Refrescar los 'matches' del sistema
POST http://localhost:8000/api/v1/job-matches/refresh
Authorization: Bearer {{auth_token}}

### Obtener los 'matches' del usuario activo
GET http://localhost:8000/api/v1/job-matches
Authorization: Bearer {{auth_token}}
