### Accede al sistema como "DESARROLLADOR" y devuelve un token.
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "dev@test.com",
    "password": "dev_password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Obtener los proyectos del usuario activo
GET http://localhost:8000/api/v1/projects
Authorization: Bearer {{auth_token}}

### Crear un proyecto, asociado al usuario activo
POST http://localhost:8000/api/v1/projects
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "title": "Nuevo Proyecto",
    "description": "Mi descripcion de Proyecto",
    "img_url": "http://mi.url/imagen.jpg"
}

> {% client.global.set("project_id", response.body.project.id); %}

### Mostrar un proyecto del usuario activo
GET http://localhost:8000/api/v1/projects/{{project_id}}
Authorization: Bearer {{auth_token}}

### Edita un proyecto del usuario activo (PUT/PATCH)
PUT http://localhost:8000/api/v1/projects/{{project_id}}
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "title": "Nuevo Proyecto Editado",
    "description": "Mi descripcion de Proyecto Editado",
    "img_url": "http://mi.url/imagen_editado.jpg"
}

### Borrar un proyecto del usuario activo
DELETE http://localhost:8000/api/v1/projects/{{project_id}}
Authorization: Bearer {{auth_token}}
