### Registra un nuevo usuario de tipo Empresa.
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "name": "Nueva Empresa",
    "email": "nuevo@empresa.com",
    "password": "mi_contraseña_segura",
    "user_type": "empresa",
    "description": "Mi Descripcion",
    "phone": "762 812 345",
    "address": "Mi Direccion de Empresa",
    "avatar": "http://cosas.jpg"
}

### Registra un nuevo usuario de tipo Desarrollador.
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "name": "Nuevo Desarrollador",
    "email": "nuevo@desarrollador.com",
    "password": "mi_contraseña_segura",
    "user_type": "desarrollador",
    "description": "Mi Descripcion",
    "phone": "456 34 23 43",
    "address": "Mi Direccion de Desarrollador",
    "avatar": "http://cosas_dev.jpg"
}

### Accede al sistema como "EMPRESA" y devuelve un token.
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "comp@test.com",
    "password": "comp_password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Accede al sistema como "DESARROLLADOR" y devuelve un token.
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "dev@test.com",
    "password": "dev_password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Devuelve el usuario activo actual
GET http://localhost:8000/api/v1/user
Authorization: Bearer {{auth_token}}


### Anula el token activo, terminando la sesion del usuario
GET http://localhost:8000/api/v1/logout
Authorization: Bearer {{auth_token}}
