### Registra un nuevo usuario de tipo Empresa.
POST http://localhost:8000/api/v1/register
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="company.png"
Content-Type: image/png

< ./img/company.png
--boundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Nueva Empresa
--boundary
Content-Disposition: form-data; name="email"
Content-Type: text/plain

nuevo@empresa.com
--boundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

mi_contraseña_segura
--boundary
Content-Disposition: form-data; name="user_type"
Content-Type: text/plain

empresa
--boundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

Mi Descripcion
--boundary
Content-Disposition: form-data; name="phone"
Content-Type: text/plain

762 812 345
--boundary
Content-Disposition: form-data; name="address"
Content-Type: text/plain

Mi Direccion de Empresa
--boundary--

### Registra un nuevo usuario de tipo Desarrollador.
POST http://localhost:8000/api/v1/register
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="developer.png"
Content-Type: image/png

< ./img/developer.png
--boundary
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Nuevo Desarrollador
--boundary
Content-Disposition: form-data; name="email"
Content-Type: text/plain

nuevo@desarrollador.com
--boundary
Content-Disposition: form-data; name="password"
Content-Type: text/plain

mi_contraseña_segura
--boundary
Content-Disposition: form-data; name="user_type"
Content-Type: text/plain

desarrollador
--boundary
Content-Disposition: form-data; name="description"
Content-Type: text/plain

Mi Descripcion
--boundary
Content-Disposition: form-data; name="phone"
Content-Type: text/plain

456 34 23 43
--boundary
Content-Disposition: form-data; name="address"
Content-Type: text/plain

Mi Direccion de Desarrollador
--boundary--

### Accede al sistema como "EMPRESA" y devuelve un token.
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "comp@test.com",
    "password": "comp_password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Accede al sistema como "DESARROLLADOR" y devuelve un token.
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "nuevo11@desarrollador.com",
    "password": "mi_contraseña_segura"
}

> {% client.global.set("auth_token", response.body.token); %}

### Devuelve el usuario activo actual
GET http://localhost:8000/api/v1/user
Authorization: Bearer {{auth_token}}

### Edita el perfil del usuario activo actual
PUT http://localhost:8000/api/v1/user
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "name": "Nombre de Usuario Editado",
    "description": "Descripcion de Usuario Editado",
    "phone": "546 34 23 65",
    "address": "La Ruta del Bacalao",
    "userable": {
        "specialization": "Ciberseguridad",
        "schedule": "Intensiva Mañana",
        "work_mode": "Teletrabajo",
        "contract_type": "Autonomo",
        "github_url": "https://github.com/lencx/ChatGPT"
    }
}

### Anula el token activo, terminando la sesion del usuario
GET http://localhost:8000/api/v1/logout
Authorization: Bearer {{auth_token}}
